# Generated by Django 6.0.5 on 2026-05-18 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('product_image', models.ImageField(upload_to='photes/products')),
                ('product_desc', models.TextField(blank=True, max_length=500)),
                ('product_price', models.IntegerField()),
                ('product_stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
