# Generated by Django 6.0.5 on 2026-05-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_old_price',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
