# Generated by Django 6.0.5 on 2026-05-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('category_slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('category_desc', models.TextField(blank=True, max_length=150)),
                ('catgegory_image', models.ImageField(blank=True, upload_to='photes/categories')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
    ]
