# Generated by Django 6.0.5 on 2026-09-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="category_desc",
        ),
        migrations.RemoveField(
            model_name="category",
            name="category_slug",
        ),
        migrations.RemoveField(
            model_name="category",
            name="catgegory_image",
        ),
        migrations.AddField(
            model_name="category",
            name="cat_image",
            field=models.ImageField(blank=True, upload_to="photos/categories"),
        ),
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
