# Generated by Django 6.0.5 on 2026-05-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='each_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
