# Generated by Django 6.0.5 on 2026-05-23 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_each_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='each_price',
        ),
    ]
